# Generated by Django 6.0.1 on 2026-01-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='Report_image')),
                ('category', models.CharField(choices=[('tv', 'Tv'), ('laptop', 'Laptop'), ('mobile', 'Mobile'), ('fridge', 'Fridge'), ('washing_mechine', 'Washing mechine')], max_length=100)),
            ],
        ),
    ]
