# Generated by Django 6.0.1 on 2026-01-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('tv', 'Tv'), ('laptop', 'Laptop'), ('mobile', 'Mobile'), ('fridge', 'Fridge'), ('tv', 'Tv'), ('washing_mechine', 'Washing mechine')], max_length=100),
        ),
    ]
